### ISSUE TITLE
Being able to view the image

### ISSUE THREAD

**Issue by mdevk093** [febryardiansyah/manga-api#12]
{"chapter_endpoint":"after-transformation-mine-and-her-wild-fantasy-chapter-70-bahasa-indonesia/","chapter_pages":12,"chapter_image":[{"chapter_image_link":"https://i0.wp.com/img.komiku.co.id/norundefined","image_number":1},{"chapter_image_link":"https://i0.wp.com/img.komiku.co.id/norundefined","image_number":2},{"chapter_image_link":"https://i0.wp.com/img.komiku.co.id/norundefined","image_number":3},{"chapter_image_link":"https://i0.wp.com/img.komiku.co.id/norundefined","image_number":4},{"chapter_image_link":"https://i0.wp.com/img.komiku.co.id/norundefined","image_number":5},{"chapter_image_link":"https://i0.wp.com/img.komiku.co.id/norundefined","image_number":6},{"chapter_image_link":"https://i0.wp.com/img.komiku.co.id/norundefined","image_number":7},{"chapter_image_link":"https://i0.wp.com/img.komiku.co.id/norundefined","image_number":8},{"chapter_image_link":"https://i0.wp.com/img.komiku.co.id/norundefined","image_number":9},{"chapter_image_link":"https://i0.wp.com/img.komiku.co.id/norundefined","image_number":10},{"chapter_image_link":"https://i0.wp.com/img.komiku.co.id/norundefined","image_number":11},{"chapter_image_link":"https://i0.wp.com/img.komiku.co.id/norundefined","image_number":12}]}

This is the data received from the chapter request, but how am i actually able to view the image? What is the string concatenation to view the image? Also, is there any way to get the image in English?

**Comment by febryardiansyah** [comment]
Hi, thanks for opening an issue
if you want to see the image just click the `chapter_image_link`, If you are using chrome browser u can install plugin named `JSONView` https://chrome.google.com/webstore/detail/jsonview/chklaanhfefbnpoihckbnefhakgolnmc. It will makes the json looks pretty.
Here's the sample image link that supposed to be shown in json https://i0.wp.com/cdn.komiku.co.id/wp-content/uploads/2236269-2.jpg , but the link is undefined because the original website has changed the html. This is the original website where the data coming from https://komiku.id/ch/%22after-transformation-mine-and-her-wild-fantasy-chapter-70-bahasa-indonesia/.
For image in English, its impossible to get. because the source just provide image in Indonesia.

I'll fix this issue as fast as possible

**Comment by febryardiansyah** [comment]
@mdevk093 Hi, i've fixed the current issue which the image link in chapter endpoint not shown as expected.
![image](https://user-images.githubusercontent.com/33514300/101479884-787fb100-3985-11eb-966d-e8c8c19cb6fc.png)
