### ISSUE TITLE
 array manga_list value null

### ISSUE THREAD

**Issue by riyaraa** [febryardiansyah/manga-api#29]
endpoint Popular & Rekomended value is null can you help me?

**Comment by riyaraa** [comment]
endpoint Popular & Rekomended value is null can you help me?

**Comment by febryardiansyah** [comment]
Hi !!! thanks for opening this issue.
this problem comes from the original website i scraped in. so, maybe u can just tell this problem to the owner of that website (komiku.id)
those endpoints get from these urls, you can check it and see the reason
https://data2.komiku.id/other/rekomendasi/
https://data3.komiku.id/other/hot/

thankyou

**Comment by febryardiansyah** [comment]
@riyaraa komiku.id already fixed, so the api now can be used like before

i'd like to close this issue, if there any question or any issue you can open new issue

thankyou
